---
title: "Untitled"
output: html_document
date: "2023-12-14"
---




```{r}
library(ggplot2)
library(dplyr)
library(readxl)
library(openxlsx)

```



```{r}
# Load dataset
data <- readxl::read_excel("/Users/Chuyuan/Downloads/dataviz_cz363_final/investor_byvc.xlsx")

data$DEAL_DATE <- as.Date(data$DEAL_DATE, format = "%Y-%m-%d")   

```



```{r}
colnames(data)
```


```{r}
# Convert DEAL_DATE to Date format
data$DEAL_DATE <- as.Date(data$DEAL_DATE)

# Extract the year from DEAL_DATE
data$YEAR <- format(data$DEAL_DATE, "%Y")

# Count the number of entries per year
yearly_counts <- table(data$YEAR)

# Print the counts for each year
print(yearly_counts)
```


```{r}
# Count the number of unique years
num_years <- length(unique(data$YEAR))

# Print the number of unique years
print(num_years)
```




```{r}

# Initial number of rows
initial_rows <- nrow(data)

# Filter out data from 2000 to 2012
data_filtered <- subset(data, YEAR > 2012)

# Number of rows after filtering
filtered_rows <- nrow(data_filtered)

# Calculate the number of rows removed
rows_removed <- initial_rows - filtered_rows

# Calculate the percentage of data removed
percentage_removed <- (rows_removed / initial_rows) * 100

# Print the percentage
print(paste("Percentage of data removed:", percentage_removed, "%"))


```



```{r}
# Convert DEAL_DATE to Date format and remove NAs

data_clean <- data_filtered %>% na.omit()
```



```{r}
# Specify the file path and name for the Excel file
file_path <- "filtered_data.xlsx"

# Write the filtered data to an Excel file
write.xlsx(data_clean, file = file_path)

```






```{r}
# Filter for a specific industry (modify as needed)
industry_of_interest <- "Healthcare"  # replace with your industry

data_check <- data_clean %>%
  filter(INDUSTRY_CLASSIFICATION == industry_of_interest)
```




```{r}
# Aggregate data by year and region
deals_by_year_region <- data_check %>%
  mutate(YEAR = year(DEAL_DATE)) %>%
  group_by(YEAR, PORTFOLIO_COMPANY_REGION) %>%
  summarise(
    Count = n(),
    Value = sum(DEAL_SIZE, na.rm = TRUE),
    .groups = 'drop'
  )


```



```{r}
# Line plot
ggplot(deals_by_year_region, aes(x = YEAR, y = Count, color = PORTFOLIO_COMPANY_REGION)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  labs(title = "Deal Count by Region and Year in Healthcare Industry",
       x = "Year", y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```










