

```{r}
library(ggplot2)
library(dplyr)
library(readxl)
library(openxlsx)
library(spData)
library(tidyr)
```


```{r}
# Load dataset
data <- readxl::read_excel("investor_byvc.xlsx")

data$DEAL_DATE <- as.Date(data$DEAL_DATE, format = "%Y-%m-%d")   

```


```{r}
colnames(data)
```


```{r}
# Convert DEAL_DATE to Date format
data$DEAL_DATE <- as.Date(data$DEAL_DATE)

# Extract the year from DEAL_DATE
data$Year <- format(data$DEAL_DATE, "%Y")

# Count the number of entries per year
yearly_counts <- table(data$Year)


print(yearly_counts)
```


```{r}

num_years <- length(unique(data$Year))

print(num_years)
```




```{r}
initial_rows <- nrow(data)

# Filter out data from 2016 to 2023
data_filtered <- subset(data, Year > 2015)

# Number of rows after filtering
filtered_rows <- nrow(data_filtered)

# Calculate the number of rows removed
rows_removed <- initial_rows - filtered_rows

# Calculate the percentage of data removed
percentage_removed <- (rows_removed / initial_rows) * 100

# Print the percentage
print(paste("Percentage of data removed:", percentage_removed, "%"))


```


```{r}
# Convert DEAL_DATE to Date format and remove NAs

data_clean <- data_filtered %>% na.omit()
```


```{r}
# Specify the file path and name for the Excel file
file_path <- "filtered_data.xlsx"

# Write the filtered data to an Excel file
write.xlsx(data_clean, file = file_path)
```
